### PR TITLE
Snapshot/Mark for Death interaction fix resolves #1528

### LINKED ISSUE #1528: Mark for Death targets only refund standard shots
I am playing the Steam release version. Targets marked with Darklance's Mark for Death only refund actions from the Sharpshooter's 2-action standard shot. Notably, Mark for Death doesn't refund Snap Shots, which was the intended use case in the most recent buff (removal of Complex Reload).

How to reproduce:
1. Have a minimal LWOTC installation
1. Install Skirmish Mode+ https://steamcommunity.com/sharedfiles/filedetails/?id=1535761480
1. Start XCOM 2 with console enabled. Start Skirmish mode.
1. Set up your squad to have at least 1 LW2 Sharpshooter, equipped with Darklance. Select some perks that grant special shots, like Snap Shot. Have at least one other soldier in your squad so that you can keep `powerup` off and still observe action economy correctly without turns ending.
1. Start the skirmish on any map
1. Add a sufficiently beefy unit to the map for the alien team, like `dropunit sectopod 2`
1. Use Mark for Death on the unit
1. Select the Sharpshooter and feed them back some actions with `giveactionpoints 2` (or `1`). Observe which skills refund spent points and which don't.

### PR DESCRIPTION
**Pull request by 1rb1s1rb1s**
Fixed Mark for Death not refunding actions on Snapshot

### CODE REVIEW

**Comment by Grobobobo** [comment]
Can you also clarify the localization description?

**Comment by 1rb1s1rb1s** [comment]
you mean specifying that it will only refund actions on standard shots and not special ones like deadeye?

**Comment by Grobobobo** [comment]
Standard shots and snapshots, yeah.

**Comment by copyrite** [comment]
While we're modifying Mark for Death's localization, could [this](https://discord.com/channels/590853492084572170/690570972117336064/896373625421180928) be included as well? From `Effect Lasts till XCOM's next turn` to `Effect lasts until the end of XCOM's next turn`.

Also `snapshots` to `Snap Shots`, if we're feeling really pedantic.

**Pull request merged**
