### PR TITLE
Jm/psilabfix

### PR DESCRIPTION
**Pull request by jmartinez989**
Fix for psi operatives not being able to train in psi lab.

### CODE REVIEW

**Comment by pledbrook** [comment]
There are too many commits in this pull request. Do you know how to fix it, or would you like some help?

**Comment by jmartinez989** [comment]
yeah sure I could use some help.

**Comment by pledbrook** [comment]
The source of the problem is that the branch you're submitting for the pull request - `jm/psilabfix` - has a different history from the branch you want to merge into, i.e. `master`. The master branch has none of the above commits, which is why git is looking to merge them.

So, you need to create a new branch that is synced with `master`, apply the change there, and then submit it as a pull request.

I don't know how you have your local repository set up, so sorry if any of the below is obvious to you and already done:

 1. Make sure you have the "long-war-2/lwotc" repository added as a remote. An easy way to do that is via the following command:
    `> git remote add https://github.com/long-war-2/lwotc.git upstream`
    This adds a remote (like the standard `origin`) called `upstream`.

 2. Make sure your local `master` branch mirrors the `master` branch of `upstream`. The easiest way to do this is via:
    ```
    > git branch -D master
    > git fetch upstream
    > git checkout -b master refs/remotes/upstream/master
    ```
    Note that you will have to be on a different branch when you delete `master`.

 3. Now create a new branch for the psi fix:
    `> git checkout -b jm/psilabfix2 master`

 4. Apply the fix to that branch. Easiest way to do this is via cherry pick:
    `> git cherry-pick b261287`
    The 'b261287' is the commit ID for the change you've already made. You're just copying it onto the new branch without any of the other commits above. You mustn't use `merge` here!

 5. Push that branch to your fork on GitHub:
    `> git push -u origin jm/psilabfilx2`

 6. Create the pull request.

From this point on, make sure that you never make local changes to `master`. Always create a new local branch and commit to that. Your local `master` branch should always mirror the _long-war-2/lwotc_ `master` branch. If you need to retrieve new commits that have been added to _long-war-2/lwotc_, simply run `git pull upstream master` while on your local `master` branch.

Hope that helps. Let me know if you need any clarification. And don't worry about getting something wrong. git makes it very hard to lose changes as long as you commit them (a good reason to commit everything, even work in progress changes).

**Comment by jmartinez989** [comment]
I can do that but just so you know I made the psi lab changes in a branch called test-changes. I then committed but did not push those changes. I made the jm/psilabfix branch locally with the command `git checkout -b jm/psilabfix test-changes`. Once I did that I pushed the branch up with `git push origin jm/psilabfix`. I never made a change to master.

**Pull request closed without merging**
