### PR TITLE
#699 Fixed Alien CCS

### PR DESCRIPTION
**Pull request by Grobobobo**
Fixed Aliens not Triggering CCS by tying
the ability to their primary weapon.
Needed to slightly change the apply
funtion for the DE version to work, and
I'm not sure I've changed it in the most efficient way.

### CODE REVIEW

**Comment by Grobobobo** [comment]
I forgot to mention, but I've taken the liberty to increase the vanguard's clip size because LW2 CCS takes 2 ammo per shot.

**Comment by pledbrook** [comment]
I'll need some time to look at this. It's not clear what's happening at all and I'm not familiar with the LW2 code in any case.

**Comment by Grobobobo** [comment]
Basically, the reason why both variants of CCS weren't working is because they weren't tied into any slot.  In vanguard's case, assigning the ability to it's primary weapon template is enough, but the dark event one requires you to assign it to the weapon during the tactical begin phase (since that's when the DE ability bonuses are assigned). The ApplyToPrimaryWeapon bool did nothing, so i changed it to specify assigning abilities to unit's primary weapons. Not sure if that helped clarify things.

**Comment by Grobobobo** [comment]
Closing to reupload later.

**Pull request closed without merging**
